/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bloomberg.api;

import com.bloomberg.api.core.ClientOptions;
import com.bloomberg.api.core.Suppliers;
import com.bloomberg.api.resources.imdb.AsyncImdbClient;
import java.util.function.Supplier;

public class AsyncBloombergApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncImdbClient> imdbClient;

    public AsyncBloombergApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new AsyncImdbClient(clientOptions));
    }

    public AsyncImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static AsyncBloombergApiClientBuilder builder() {
        return new AsyncBloombergApiClientBuilder();
    }
}
