/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bloomberg.api;

import com.bloomberg.api.core.ClientOptions;
import com.bloomberg.api.core.Suppliers;
import com.bloomberg.api.resources.imdb.ImdbClient;
import java.util.function.Supplier;

public class BloombergApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ImdbClient> imdbClient;

    public BloombergApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new ImdbClient(clientOptions));
    }

    public ImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static BloombergApiClientBuilder builder() {
        return new BloombergApiClientBuilder();
    }
}
