/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bloomberg.api;

import com.bloomberg.api.core.ClientOptions;
import com.bloomberg.api.core.Environment;
import okhttp3.OkHttpClient;

public final class BloombergApiClientBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private Environment environment;

    public BloombergApiClientBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    /**
     * Sets the timeout (in seconds) for the client. Defaults to 60 seconds.
     */
    public BloombergApiClientBuilder timeout(int timeout) {
        this.clientOptionsBuilder.timeout(timeout);
        return this;
    }

    /**
     * Sets the maximum number of retries for the client. Defaults to 2 retries.
     */
    public BloombergApiClientBuilder maxRetries(int maxRetries) {
        this.clientOptionsBuilder.maxRetries(maxRetries);
        return this;
    }

    /**
     * Sets the underlying OkHttp client
     */
    public BloombergApiClientBuilder httpClient(OkHttpClient httpClient) {
        this.clientOptionsBuilder.httpClient(httpClient);
        return this;
    }

    public BloombergApiClient build() {
        clientOptionsBuilder.environment(this.environment);
        return new BloombergApiClient(clientOptionsBuilder.build());
    }
}
