/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bloomberg.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class BloombergApiException extends RuntimeException {
    public BloombergApiException(String message) {
        super(message);
    }

    public BloombergApiException(String message, Exception e) {
        super(message, e);
    }
}
