/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.plantstore.api;

import com.plantstore.api.core.ClientOptions;
import com.plantstore.api.core.Environment;
import okhttp3.OkHttpClient;

public final class AsyncPlantstoreApiClientBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private Environment environment;

    public AsyncPlantstoreApiClientBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    /**
     * Sets the timeout (in seconds) for the client. Defaults to 60 seconds.
     */
    public AsyncPlantstoreApiClientBuilder timeout(int timeout) {
        this.clientOptionsBuilder.timeout(timeout);
        return this;
    }

    /**
     * Sets the maximum number of retries for the client. Defaults to 2 retries.
     */
    public AsyncPlantstoreApiClientBuilder maxRetries(int maxRetries) {
        this.clientOptionsBuilder.maxRetries(maxRetries);
        return this;
    }

    /**
     * Sets the underlying OkHttp client
     */
    public AsyncPlantstoreApiClientBuilder httpClient(OkHttpClient httpClient) {
        this.clientOptionsBuilder.httpClient(httpClient);
        return this;
    }

    public AsyncPlantstoreApiClient build() {
        clientOptionsBuilder.environment(this.environment);
        return new AsyncPlantstoreApiClient(clientOptionsBuilder.build());
    }
}
