/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.plantstore.api;

import com.plantstore.api.core.ClientOptions;
import com.plantstore.api.core.Suppliers;
import com.plantstore.api.resources.imdb.AsyncImdbClient;
import java.util.function.Supplier;

public class AsyncPlantstoreApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncImdbClient> imdbClient;

    public AsyncPlantstoreApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new AsyncImdbClient(clientOptions));
    }

    public AsyncImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static AsyncPlantstoreApiClientBuilder builder() {
        return new AsyncPlantstoreApiClientBuilder();
    }
}
