/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.plantstore.api;

import com.plantstore.api.core.ClientOptions;
import com.plantstore.api.core.Suppliers;
import com.plantstore.api.resources.imdb.ImdbClient;
import java.util.function.Supplier;

public class PlantstoreApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ImdbClient> imdbClient;

    public PlantstoreApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.imdbClient = Suppliers.memoize(() -> new ImdbClient(clientOptions));
    }

    public ImdbClient imdb() {
        return this.imdbClient.get();
    }

    public static PlantstoreApiClientBuilder builder() {
        return new PlantstoreApiClientBuilder();
    }
}
