/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.plantstore.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class PlantstoreApiException extends RuntimeException {
    public PlantstoreApiException(String message) {
        super(message);
    }

    public PlantstoreApiException(String message, Exception e) {
        super(message, e);
    }
}
